package com.eStudent.user.student;

public enum Majors {
	BUSINESS_ECONOMICS, INFORMATION_TECHNOLOGY, ELECTRICAL_ENGINEERING_AND_COMPUTING,
	SOFTWARE_AND_INFORMATION_ENGINEERING, PSHYSICAL_EDUCATION_AND_SPORTS, TOURISM_AND_HOSPITALITY;
}
